### ISSUE TITLE
Anomalies in src\plug\dimmers

### ISSUE THREAD

**Issue by DaveGut** [plasticrake/tplink-smarthome-api#129]
First - as usual thanks for the great examples in your files.  I was finalizing my Hubitat Dimming Switch Driver and noted the following anomalies:

async **setDimmerTransition**:  This command takes either mode or brightness.  If mode is expressed, brightness is ignored.  For mode, it takes "gentle_on_off" or "instant_on_off". 

async **setGentleOffTime** and **setGentleOnTime**:  This commands uses "duration" instead of "fadeTime".

Dave Gutheinz

**Comment by plasticrake** [comment]
**setDimmerTransition**: Is there an issue around this? Currently in the code it can take 3 parameters but they are each optional. And since JSON.stringify is run on them, any undefined keys would be removed from the object. That should let you ignore brightness for example.

**setGentleOffTime**: You're right! I don't have these devices but I think I copied something incorrectly from my notes. I'll fix this
