### ISSUE TITLE
Australian Version and Energy Monitoring

### ISSUE THREAD

**Issue by DaveGut** [plasticrake/tplink-smarthome-api#41]
From my SmartThings integration, I received a problem that the Energy Monitor failed on the HS110(AU) version.  My verified evaluation (for your consideration) is that on the AU firmware, they change the output messages for 'get_realtime' and 'get_daystat'.

For get_daystat, the daily cell, which is now similar to the below (after the groovy Json parse)
["month":1, "year":2018, "day":26, "energy_wh":2043]

For get_realtime, the and example message is now:
[emeter:[get_realtime:[err_code:0, current_ma: 755, total_wh:2155, power_mw:17532, voltage_mv:243236]]]

Two notes:
1.  The data value formats above are identical with the BULB energy meter return data.
2.  The get_realtime total_wh is not used to display today's usage in the Kasa App.  It continues to use the current day's value from the get_daystat return.

Thanks for all your work.

**Comment by ironsm4sh** [comment]
I have a HS110 in Europe, its output messages and Kasa app behavior is identical to yours.

**Comment by plasticrake** [comment]
Hi @DaveGut, I don't think this is an issue anymore. I know work was done to help support these devices awhile ago. This program has been normalizing the getRealtime output to output by the new and old properties. Fixed in v0.23.0

Closing this as its old, if you still have a problem please create a new issue. Thanks!

Related: plasticrake/homebridge-tplink-smarthome#57
