### ISSUE TITLE
Specify which network/interface to run on?

### ISSUE THREAD

**Issue by eugenekolo** [plasticrake/tplink-smarthome-api#69]
The device I'm running this on has an eth0, and wlan0 (ethernet and wifi). They're different networks. You can imagine a similar set up with multiple Wifi cards.

Is there a way to specify which network/interface to use?

**Comment by plasticrake** [comment]
Do you mean for discovery? You can pass in the address you want to bind to for startDiscovery.

**Comment by sstormm** [comment]
> The device I'm running this on has an eth0, and wlan0 (ethernet and wifi). They're different networks. You can imagine a similar set up with multiple Wifi cards.
> 
> Is there a way to specify which network/interface to use?

I think i know what you're asking because i had a similar issue.  the API doesn't allow you to specify an interface name AFAIK. what the API needs is discovery options that include the "broadcast" address. in order to get that, you need to get the current IP address of a specific interface.  we just hardcoded an interface name into a config file (ex/ "wlan0") and then used the following function (found via google searches) to enumerate the interfaces and IP addresses.

```getNetworkInterfaces() {
        var
        // Local ip address that we're trying to calculate
        address
        // Provides a few basic operating-system related utility functions (built-in)
        ,os = require('os')
        // Network interfaces
        ,ifaces = os.networkInterfaces();
        let interfaces = {};
        
        // Iterate over interfaces ...
        for (var dev in ifaces) {
            // ... and find the one that matches the criteria
            var iface = ifaces[dev].filter(function(details) {
                return details.family === 'IPv4' && details.internal === false;
            });
            if (iface[0]) {
                interfaces[dev] = iface[0];
            }
        }

        return interfaces;
    }
```

once you get the IP address for the interface you're interested in, then you can just calculate the broadcast address by replacing the last IP field by 255.  so if you want to use "wlan0" and its IP is 192.168.1.123 then you use broadcast 192.168.1.255.

**Comment by eugenekolo** [comment]
Hey @plasticrake and @sstormm , thanks for the help!

Yes, that's what I wanted @sstormm. I believe @plasticrake's answer is similar in telling me to specify the IP instead of the interface. 

I ended up doing another option of just modifying some of the functions.

I added 
```
socket.setMulticastInterface('192.168.0.1');
``` 
to the dgram.socket's bind call for UDP.

And 
```
localAddress: '192.168.0.1'
```
to the net.socket's connect call for TCP.

I believe those two changes worked for what I wanted.
